#!/bin/bash
answer="Purple and Blue"
userInput=" "

clear
echo
until [ "$userInput" = "$answer" ]
do
  read -p "What names did you end up making out? " userInput
  if [ "$userInput" != "$answer" ]
  then
    echo 
    echo "[ANSWER: $userInput]"
    echo "[WRONG. PLEASE TRY AGAIN.]"
    echo "[HINT: P___ and B___]"
    echo
  fi
done
echo " "
echo "Purple and Blue. I'll be sure to keep them in mind."

cat ../../clues/securityRoomTask1Clue.txt
cp ../../clues/securityRoomTask1Clue.txt ../../pockets/securityRoomClue1.txt

RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "[${RED}Admin Clue ${NC}has been found! You can access it at any time via the ${BLUE}foundClues ${NC}directory in your pocket.]"
echo
echo -e "[You can go back to the ship's main hub by typing ${RED}cd ..${NC}. This will change your working directory back to the previous directory.]"
echo -e "[Of course, you can also use the ${RED}ls ${NC}command to see where else you can go from the hub.]"
echo -e "[Similarly, typing ${RED}cd "directoryName" ${NC}can be used to change your working directory to any room you see in the hub.]"
echo -e "[If you ever get lost, you can always use the ${RED}pwd ${NC}command to remind yourself where you are.]"
echo
